// Nigerian banks list (fintechs + commercial). Alphabetical.
export const NG_BANKS: string[] = [
  "Access Bank",
  "Access Bank (Diamond)",
  "ALAT by Wema",
  "Carbon",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "FairMoney Microfinance Bank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "GoMoney",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "Lotus Bank",
  "Mint Finex MFB",
  "Moniepoint MFB",
  "OPay",
  "Paga",
  "PalmPay",
  "Parallex Bank",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Rubies MFB",
  "Sparkle Microfinance Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
];
